# \
CS 4375 - Theory of Operating Systems\
By: Matthew Iglesias (ID: 80591632)\
By: Matthew S Montoya (ID: 88606727)\
Purpose: To build a user shell for a Unix operating system\
Last Modified: 28 February 2020

unixshell.o: UnixShell.c UserInput.c ShellGreeting.c
	gcc UnixShell.c UserInput.c ShellGreeting.c -o unixshell.o
clean:
	rm -f *.o